DB_DRIVER_NAME: "local"
DB_SOURCE: "local"
SESSION_SECRET_KEY: "local"
JWT_SECRET_KEY: "local"
GOOGLE_CLIENT_ID: "local"
GOOGLE_CLIENT_SECRET: "local"
WEB_URL: "http://localhost:3000"
ENCRYPTION_KEY: "local"
AWS_REGION: "local"
DYNAMO_IS_LOCAL: "local"
MESSAGING_PLATFORM: "local"
SQS_QUEUE_URL: "local"
TEST_UPBIT_KEY: "local"
TEST_UPBIT_SECRET: "local"
TEST_BINANCE_KEY: "local"
TEST_BINANCE_SECRET: "local"