version: "3.3"
services:
  falcon-dynamodb:
    container_name: falcon-dynamodb
    image: amazon/dynamodb-local
    #    restart: always
    restart: always
    volumes:
      - ./.dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

volumes:
  app-db-data:

networks:
  falcon-net:
    driver: bridge
