version: "3.3"
services:
  falcon-db:
    container_name: falcon-db
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=falcon
    networks:
      - falcon-net

volumes:
  app-db-data:

networks:
  falcon-net:
    driver: bridge
