// Code generated by ent, DO NOT EDIT.

package tradingaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ugabiga/falcon/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldUserID, v))
}

// Exchange applies equality check predicate on the "exchange" field. It's identical to ExchangeEQ.
func Exchange(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldExchange, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldCurrency, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldIP, v))
}

// Identifier applies equality check predicate on the "identifier" field. It's identical to IdentifierEQ.
func Identifier(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldIdentifier, v))
}

// Credential applies equality check predicate on the "credential" field. It's identical to CredentialEQ.
func Credential(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldCredential, v))
}

// Phrase applies equality check predicate on the "phrase" field. It's identical to PhraseEQ.
func Phrase(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldPhrase, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldUserID, vs...))
}

// ExchangeEQ applies the EQ predicate on the "exchange" field.
func ExchangeEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldExchange, v))
}

// ExchangeNEQ applies the NEQ predicate on the "exchange" field.
func ExchangeNEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldExchange, v))
}

// ExchangeIn applies the In predicate on the "exchange" field.
func ExchangeIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldExchange, vs...))
}

// ExchangeNotIn applies the NotIn predicate on the "exchange" field.
func ExchangeNotIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldExchange, vs...))
}

// ExchangeGT applies the GT predicate on the "exchange" field.
func ExchangeGT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldExchange, v))
}

// ExchangeGTE applies the GTE predicate on the "exchange" field.
func ExchangeGTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldExchange, v))
}

// ExchangeLT applies the LT predicate on the "exchange" field.
func ExchangeLT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldExchange, v))
}

// ExchangeLTE applies the LTE predicate on the "exchange" field.
func ExchangeLTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldExchange, v))
}

// ExchangeContains applies the Contains predicate on the "exchange" field.
func ExchangeContains(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContains(FieldExchange, v))
}

// ExchangeHasPrefix applies the HasPrefix predicate on the "exchange" field.
func ExchangeHasPrefix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasPrefix(FieldExchange, v))
}

// ExchangeHasSuffix applies the HasSuffix predicate on the "exchange" field.
func ExchangeHasSuffix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasSuffix(FieldExchange, v))
}

// ExchangeEqualFold applies the EqualFold predicate on the "exchange" field.
func ExchangeEqualFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEqualFold(FieldExchange, v))
}

// ExchangeContainsFold applies the ContainsFold predicate on the "exchange" field.
func ExchangeContainsFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContainsFold(FieldExchange, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContainsFold(FieldCurrency, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContainsFold(FieldIP, v))
}

// IdentifierEQ applies the EQ predicate on the "identifier" field.
func IdentifierEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldIdentifier, v))
}

// IdentifierNEQ applies the NEQ predicate on the "identifier" field.
func IdentifierNEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldIdentifier, v))
}

// IdentifierIn applies the In predicate on the "identifier" field.
func IdentifierIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldIdentifier, vs...))
}

// IdentifierNotIn applies the NotIn predicate on the "identifier" field.
func IdentifierNotIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldIdentifier, vs...))
}

// IdentifierGT applies the GT predicate on the "identifier" field.
func IdentifierGT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldIdentifier, v))
}

// IdentifierGTE applies the GTE predicate on the "identifier" field.
func IdentifierGTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldIdentifier, v))
}

// IdentifierLT applies the LT predicate on the "identifier" field.
func IdentifierLT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldIdentifier, v))
}

// IdentifierLTE applies the LTE predicate on the "identifier" field.
func IdentifierLTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldIdentifier, v))
}

// IdentifierContains applies the Contains predicate on the "identifier" field.
func IdentifierContains(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContains(FieldIdentifier, v))
}

// IdentifierHasPrefix applies the HasPrefix predicate on the "identifier" field.
func IdentifierHasPrefix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasPrefix(FieldIdentifier, v))
}

// IdentifierHasSuffix applies the HasSuffix predicate on the "identifier" field.
func IdentifierHasSuffix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasSuffix(FieldIdentifier, v))
}

// IdentifierEqualFold applies the EqualFold predicate on the "identifier" field.
func IdentifierEqualFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEqualFold(FieldIdentifier, v))
}

// IdentifierContainsFold applies the ContainsFold predicate on the "identifier" field.
func IdentifierContainsFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContainsFold(FieldIdentifier, v))
}

// CredentialEQ applies the EQ predicate on the "credential" field.
func CredentialEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldCredential, v))
}

// CredentialNEQ applies the NEQ predicate on the "credential" field.
func CredentialNEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldCredential, v))
}

// CredentialIn applies the In predicate on the "credential" field.
func CredentialIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldCredential, vs...))
}

// CredentialNotIn applies the NotIn predicate on the "credential" field.
func CredentialNotIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldCredential, vs...))
}

// CredentialGT applies the GT predicate on the "credential" field.
func CredentialGT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldCredential, v))
}

// CredentialGTE applies the GTE predicate on the "credential" field.
func CredentialGTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldCredential, v))
}

// CredentialLT applies the LT predicate on the "credential" field.
func CredentialLT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldCredential, v))
}

// CredentialLTE applies the LTE predicate on the "credential" field.
func CredentialLTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldCredential, v))
}

// CredentialContains applies the Contains predicate on the "credential" field.
func CredentialContains(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContains(FieldCredential, v))
}

// CredentialHasPrefix applies the HasPrefix predicate on the "credential" field.
func CredentialHasPrefix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasPrefix(FieldCredential, v))
}

// CredentialHasSuffix applies the HasSuffix predicate on the "credential" field.
func CredentialHasSuffix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasSuffix(FieldCredential, v))
}

// CredentialEqualFold applies the EqualFold predicate on the "credential" field.
func CredentialEqualFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEqualFold(FieldCredential, v))
}

// CredentialContainsFold applies the ContainsFold predicate on the "credential" field.
func CredentialContainsFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContainsFold(FieldCredential, v))
}

// PhraseEQ applies the EQ predicate on the "phrase" field.
func PhraseEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldPhrase, v))
}

// PhraseNEQ applies the NEQ predicate on the "phrase" field.
func PhraseNEQ(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldPhrase, v))
}

// PhraseIn applies the In predicate on the "phrase" field.
func PhraseIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldPhrase, vs...))
}

// PhraseNotIn applies the NotIn predicate on the "phrase" field.
func PhraseNotIn(vs ...string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldPhrase, vs...))
}

// PhraseGT applies the GT predicate on the "phrase" field.
func PhraseGT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldPhrase, v))
}

// PhraseGTE applies the GTE predicate on the "phrase" field.
func PhraseGTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldPhrase, v))
}

// PhraseLT applies the LT predicate on the "phrase" field.
func PhraseLT(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldPhrase, v))
}

// PhraseLTE applies the LTE predicate on the "phrase" field.
func PhraseLTE(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldPhrase, v))
}

// PhraseContains applies the Contains predicate on the "phrase" field.
func PhraseContains(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContains(FieldPhrase, v))
}

// PhraseHasPrefix applies the HasPrefix predicate on the "phrase" field.
func PhraseHasPrefix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasPrefix(FieldPhrase, v))
}

// PhraseHasSuffix applies the HasSuffix predicate on the "phrase" field.
func PhraseHasSuffix(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldHasSuffix(FieldPhrase, v))
}

// PhraseEqualFold applies the EqualFold predicate on the "phrase" field.
func PhraseEqualFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEqualFold(FieldPhrase, v))
}

// PhraseContainsFold applies the ContainsFold predicate on the "phrase" field.
func PhraseContainsFold(v string) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldContainsFold(FieldPhrase, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TradingAccount {
	return predicate.TradingAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TradingAccount {
	return predicate.TradingAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TradingAccount {
	return predicate.TradingAccount(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.TradingAccount {
	return predicate.TradingAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.Task) predicate.TradingAccount {
	return predicate.TradingAccount(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TradingAccount) predicate.TradingAccount {
	return predicate.TradingAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TradingAccount) predicate.TradingAccount {
	return predicate.TradingAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TradingAccount) predicate.TradingAccount {
	return predicate.TradingAccount(sql.NotPredicates(p))
}
