// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ugabiga/falcon/internal/ent/task"
	"github.com/ugabiga/falcon/internal/ent/taskhistory"
)

// TaskHistoryCreate is the builder for creating a TaskHistory entity.
type TaskHistoryCreate struct {
	config
	mutation *TaskHistoryMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (thc *TaskHistoryCreate) SetTaskID(u uint64) *TaskHistoryCreate {
	thc.mutation.SetTaskID(u)
	return thc
}

// SetIsSuccess sets the "is_success" field.
func (thc *TaskHistoryCreate) SetIsSuccess(b bool) *TaskHistoryCreate {
	thc.mutation.SetIsSuccess(b)
	return thc
}

// SetUpdatedAt sets the "updated_at" field.
func (thc *TaskHistoryCreate) SetUpdatedAt(t time.Time) *TaskHistoryCreate {
	thc.mutation.SetUpdatedAt(t)
	return thc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (thc *TaskHistoryCreate) SetNillableUpdatedAt(t *time.Time) *TaskHistoryCreate {
	if t != nil {
		thc.SetUpdatedAt(*t)
	}
	return thc
}

// SetCreatedAt sets the "created_at" field.
func (thc *TaskHistoryCreate) SetCreatedAt(t time.Time) *TaskHistoryCreate {
	thc.mutation.SetCreatedAt(t)
	return thc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (thc *TaskHistoryCreate) SetNillableCreatedAt(t *time.Time) *TaskHistoryCreate {
	if t != nil {
		thc.SetCreatedAt(*t)
	}
	return thc
}

// SetID sets the "id" field.
func (thc *TaskHistoryCreate) SetID(u uint64) *TaskHistoryCreate {
	thc.mutation.SetID(u)
	return thc
}

// SetTask sets the "task" edge to the Task entity.
func (thc *TaskHistoryCreate) SetTask(t *Task) *TaskHistoryCreate {
	return thc.SetTaskID(t.ID)
}

// Mutation returns the TaskHistoryMutation object of the builder.
func (thc *TaskHistoryCreate) Mutation() *TaskHistoryMutation {
	return thc.mutation
}

// Save creates the TaskHistory in the database.
func (thc *TaskHistoryCreate) Save(ctx context.Context) (*TaskHistory, error) {
	thc.defaults()
	return withHooks(ctx, thc.sqlSave, thc.mutation, thc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (thc *TaskHistoryCreate) SaveX(ctx context.Context) *TaskHistory {
	v, err := thc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (thc *TaskHistoryCreate) Exec(ctx context.Context) error {
	_, err := thc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thc *TaskHistoryCreate) ExecX(ctx context.Context) {
	if err := thc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (thc *TaskHistoryCreate) defaults() {
	if _, ok := thc.mutation.UpdatedAt(); !ok {
		v := taskhistory.DefaultUpdatedAt()
		thc.mutation.SetUpdatedAt(v)
	}
	if _, ok := thc.mutation.CreatedAt(); !ok {
		v := taskhistory.DefaultCreatedAt()
		thc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (thc *TaskHistoryCreate) check() error {
	if _, ok := thc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "TaskHistory.task_id"`)}
	}
	if v, ok := thc.mutation.TaskID(); ok {
		if err := taskhistory.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.task_id": %w`, err)}
		}
	}
	if _, ok := thc.mutation.IsSuccess(); !ok {
		return &ValidationError{Name: "is_success", err: errors.New(`ent: missing required field "TaskHistory.is_success"`)}
	}
	if _, ok := thc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TaskHistory.updated_at"`)}
	}
	if _, ok := thc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TaskHistory.created_at"`)}
	}
	if v, ok := thc.mutation.ID(); ok {
		if err := taskhistory.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.id": %w`, err)}
		}
	}
	if _, ok := thc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskHistory.task"`)}
	}
	return nil
}

func (thc *TaskHistoryCreate) sqlSave(ctx context.Context) (*TaskHistory, error) {
	if err := thc.check(); err != nil {
		return nil, err
	}
	_node, _spec := thc.createSpec()
	if err := sqlgraph.CreateNode(ctx, thc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	thc.mutation.id = &_node.ID
	thc.mutation.done = true
	return _node, nil
}

func (thc *TaskHistoryCreate) createSpec() (*TaskHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskHistory{config: thc.config}
		_spec = sqlgraph.NewCreateSpec(taskhistory.Table, sqlgraph.NewFieldSpec(taskhistory.FieldID, field.TypeUint64))
	)
	if id, ok := thc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := thc.mutation.IsSuccess(); ok {
		_spec.SetField(taskhistory.FieldIsSuccess, field.TypeBool, value)
		_node.IsSuccess = value
	}
	if value, ok := thc.mutation.UpdatedAt(); ok {
		_spec.SetField(taskhistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := thc.mutation.CreatedAt(); ok {
		_spec.SetField(taskhistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := thc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskHistoryCreateBulk is the builder for creating many TaskHistory entities in bulk.
type TaskHistoryCreateBulk struct {
	config
	err      error
	builders []*TaskHistoryCreate
}

// Save creates the TaskHistory entities in the database.
func (thcb *TaskHistoryCreateBulk) Save(ctx context.Context) ([]*TaskHistory, error) {
	if thcb.err != nil {
		return nil, thcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(thcb.builders))
	nodes := make([]*TaskHistory, len(thcb.builders))
	mutators := make([]Mutator, len(thcb.builders))
	for i := range thcb.builders {
		func(i int, root context.Context) {
			builder := thcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, thcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, thcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, thcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (thcb *TaskHistoryCreateBulk) SaveX(ctx context.Context) []*TaskHistory {
	v, err := thcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (thcb *TaskHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := thcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thcb *TaskHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := thcb.Exec(ctx); err != nil {
		panic(err)
	}
}
