// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ugabiga/falcon/internal/ent/predicate"
	"github.com/ugabiga/falcon/internal/ent/task"
	"github.com/ugabiga/falcon/internal/ent/tradingaccount"
	"github.com/ugabiga/falcon/internal/ent/user"
)

// TradingAccountQuery is the builder for querying TradingAccount entities.
type TradingAccountQuery struct {
	config
	ctx        *QueryContext
	order      []tradingaccount.OrderOption
	inters     []Interceptor
	predicates []predicate.TradingAccount
	withUser   *UserQuery
	withTasks  *TaskQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TradingAccountQuery builder.
func (taq *TradingAccountQuery) Where(ps ...predicate.TradingAccount) *TradingAccountQuery {
	taq.predicates = append(taq.predicates, ps...)
	return taq
}

// Limit the number of records to be returned by this query.
func (taq *TradingAccountQuery) Limit(limit int) *TradingAccountQuery {
	taq.ctx.Limit = &limit
	return taq
}

// Offset to start from.
func (taq *TradingAccountQuery) Offset(offset int) *TradingAccountQuery {
	taq.ctx.Offset = &offset
	return taq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (taq *TradingAccountQuery) Unique(unique bool) *TradingAccountQuery {
	taq.ctx.Unique = &unique
	return taq
}

// Order specifies how the records should be ordered.
func (taq *TradingAccountQuery) Order(o ...tradingaccount.OrderOption) *TradingAccountQuery {
	taq.order = append(taq.order, o...)
	return taq
}

// QueryUser chains the current query on the "user" edge.
func (taq *TradingAccountQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: taq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := taq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tradingaccount.Table, tradingaccount.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tradingaccount.UserTable, tradingaccount.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(taq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTasks chains the current query on the "tasks" edge.
func (taq *TradingAccountQuery) QueryTasks() *TaskQuery {
	query := (&TaskClient{config: taq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := taq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tradingaccount.Table, tradingaccount.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tradingaccount.TasksTable, tradingaccount.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(taq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TradingAccount entity from the query.
// Returns a *NotFoundError when no TradingAccount was found.
func (taq *TradingAccountQuery) First(ctx context.Context) (*TradingAccount, error) {
	nodes, err := taq.Limit(1).All(setContextOp(ctx, taq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tradingaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (taq *TradingAccountQuery) FirstX(ctx context.Context) *TradingAccount {
	node, err := taq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TradingAccount ID from the query.
// Returns a *NotFoundError when no TradingAccount ID was found.
func (taq *TradingAccountQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = taq.Limit(1).IDs(setContextOp(ctx, taq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tradingaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (taq *TradingAccountQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := taq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TradingAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TradingAccount entity is found.
// Returns a *NotFoundError when no TradingAccount entities are found.
func (taq *TradingAccountQuery) Only(ctx context.Context) (*TradingAccount, error) {
	nodes, err := taq.Limit(2).All(setContextOp(ctx, taq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tradingaccount.Label}
	default:
		return nil, &NotSingularError{tradingaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (taq *TradingAccountQuery) OnlyX(ctx context.Context) *TradingAccount {
	node, err := taq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TradingAccount ID in the query.
// Returns a *NotSingularError when more than one TradingAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (taq *TradingAccountQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = taq.Limit(2).IDs(setContextOp(ctx, taq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tradingaccount.Label}
	default:
		err = &NotSingularError{tradingaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (taq *TradingAccountQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := taq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TradingAccounts.
func (taq *TradingAccountQuery) All(ctx context.Context) ([]*TradingAccount, error) {
	ctx = setContextOp(ctx, taq.ctx, "All")
	if err := taq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TradingAccount, *TradingAccountQuery]()
	return withInterceptors[[]*TradingAccount](ctx, taq, qr, taq.inters)
}

// AllX is like All, but panics if an error occurs.
func (taq *TradingAccountQuery) AllX(ctx context.Context) []*TradingAccount {
	nodes, err := taq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TradingAccount IDs.
func (taq *TradingAccountQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if taq.ctx.Unique == nil && taq.path != nil {
		taq.Unique(true)
	}
	ctx = setContextOp(ctx, taq.ctx, "IDs")
	if err = taq.Select(tradingaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (taq *TradingAccountQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := taq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (taq *TradingAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, taq.ctx, "Count")
	if err := taq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, taq, querierCount[*TradingAccountQuery](), taq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (taq *TradingAccountQuery) CountX(ctx context.Context) int {
	count, err := taq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (taq *TradingAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, taq.ctx, "Exist")
	switch _, err := taq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (taq *TradingAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := taq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TradingAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (taq *TradingAccountQuery) Clone() *TradingAccountQuery {
	if taq == nil {
		return nil
	}
	return &TradingAccountQuery{
		config:     taq.config,
		ctx:        taq.ctx.Clone(),
		order:      append([]tradingaccount.OrderOption{}, taq.order...),
		inters:     append([]Interceptor{}, taq.inters...),
		predicates: append([]predicate.TradingAccount{}, taq.predicates...),
		withUser:   taq.withUser.Clone(),
		withTasks:  taq.withTasks.Clone(),
		// clone intermediate query.
		sql:  taq.sql.Clone(),
		path: taq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (taq *TradingAccountQuery) WithUser(opts ...func(*UserQuery)) *TradingAccountQuery {
	query := (&UserClient{config: taq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	taq.withUser = query
	return taq
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (taq *TradingAccountQuery) WithTasks(opts ...func(*TaskQuery)) *TradingAccountQuery {
	query := (&TaskClient{config: taq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	taq.withTasks = query
	return taq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Exchange string `json:"exchange,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TradingAccount.Query().
//		GroupBy(tradingaccount.FieldExchange).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (taq *TradingAccountQuery) GroupBy(field string, fields ...string) *TradingAccountGroupBy {
	taq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TradingAccountGroupBy{build: taq}
	grbuild.flds = &taq.ctx.Fields
	grbuild.label = tradingaccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Exchange string `json:"exchange,omitempty"`
//	}
//
//	client.TradingAccount.Query().
//		Select(tradingaccount.FieldExchange).
//		Scan(ctx, &v)
func (taq *TradingAccountQuery) Select(fields ...string) *TradingAccountSelect {
	taq.ctx.Fields = append(taq.ctx.Fields, fields...)
	sbuild := &TradingAccountSelect{TradingAccountQuery: taq}
	sbuild.label = tradingaccount.Label
	sbuild.flds, sbuild.scan = &taq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TradingAccountSelect configured with the given aggregations.
func (taq *TradingAccountQuery) Aggregate(fns ...AggregateFunc) *TradingAccountSelect {
	return taq.Select().Aggregate(fns...)
}

func (taq *TradingAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range taq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, taq); err != nil {
				return err
			}
		}
	}
	for _, f := range taq.ctx.Fields {
		if !tradingaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if taq.path != nil {
		prev, err := taq.path(ctx)
		if err != nil {
			return err
		}
		taq.sql = prev
	}
	return nil
}

func (taq *TradingAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TradingAccount, error) {
	var (
		nodes       = []*TradingAccount{}
		withFKs     = taq.withFKs
		_spec       = taq.querySpec()
		loadedTypes = [2]bool{
			taq.withUser != nil,
			taq.withTasks != nil,
		}
	)
	if taq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tradingaccount.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TradingAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TradingAccount{config: taq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, taq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := taq.withUser; query != nil {
		if err := taq.loadUser(ctx, query, nodes, nil,
			func(n *TradingAccount, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := taq.withTasks; query != nil {
		if err := taq.loadTasks(ctx, query, nodes,
			func(n *TradingAccount) { n.Edges.Tasks = []*Task{} },
			func(n *TradingAccount, e *Task) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (taq *TradingAccountQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*TradingAccount, init func(*TradingAccount), assign func(*TradingAccount, *User)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*TradingAccount)
	for i := range nodes {
		if nodes[i].user_trading_accounts == nil {
			continue
		}
		fk := *nodes[i].user_trading_accounts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_trading_accounts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (taq *TradingAccountQuery) loadTasks(ctx context.Context, query *TaskQuery, nodes []*TradingAccount, init func(*TradingAccount), assign func(*TradingAccount, *Task)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*TradingAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Task(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tradingaccount.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.trading_account_tasks
		if fk == nil {
			return fmt.Errorf(`foreign-key "trading_account_tasks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "trading_account_tasks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (taq *TradingAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := taq.querySpec()
	_spec.Node.Columns = taq.ctx.Fields
	if len(taq.ctx.Fields) > 0 {
		_spec.Unique = taq.ctx.Unique != nil && *taq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, taq.driver, _spec)
}

func (taq *TradingAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tradingaccount.Table, tradingaccount.Columns, sqlgraph.NewFieldSpec(tradingaccount.FieldID, field.TypeUint64))
	_spec.From = taq.sql
	if unique := taq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if taq.path != nil {
		_spec.Unique = true
	}
	if fields := taq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tradingaccount.FieldID)
		for i := range fields {
			if fields[i] != tradingaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := taq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := taq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := taq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := taq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (taq *TradingAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(taq.driver.Dialect())
	t1 := builder.Table(tradingaccount.Table)
	columns := taq.ctx.Fields
	if len(columns) == 0 {
		columns = tradingaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if taq.sql != nil {
		selector = taq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if taq.ctx.Unique != nil && *taq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range taq.predicates {
		p(selector)
	}
	for _, p := range taq.order {
		p(selector)
	}
	if offset := taq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := taq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TradingAccountGroupBy is the group-by builder for TradingAccount entities.
type TradingAccountGroupBy struct {
	selector
	build *TradingAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tagb *TradingAccountGroupBy) Aggregate(fns ...AggregateFunc) *TradingAccountGroupBy {
	tagb.fns = append(tagb.fns, fns...)
	return tagb
}

// Scan applies the selector query and scans the result into the given value.
func (tagb *TradingAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tagb.build.ctx, "GroupBy")
	if err := tagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TradingAccountQuery, *TradingAccountGroupBy](ctx, tagb.build, tagb, tagb.build.inters, v)
}

func (tagb *TradingAccountGroupBy) sqlScan(ctx context.Context, root *TradingAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tagb.fns))
	for _, fn := range tagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tagb.flds)+len(tagb.fns))
		for _, f := range *tagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TradingAccountSelect is the builder for selecting fields of TradingAccount entities.
type TradingAccountSelect struct {
	*TradingAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tas *TradingAccountSelect) Aggregate(fns ...AggregateFunc) *TradingAccountSelect {
	tas.fns = append(tas.fns, fns...)
	return tas
}

// Scan applies the selector query and scans the result into the given value.
func (tas *TradingAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tas.ctx, "Select")
	if err := tas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TradingAccountQuery, *TradingAccountSelect](ctx, tas.TradingAccountQuery, tas, tas.inters, v)
}

func (tas *TradingAccountSelect) sqlScan(ctx context.Context, root *TradingAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tas.fns))
	for _, fn := range tas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
