// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authentication is the predicate function for authentication builders.
type Authentication func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskHistory is the predicate function for taskhistory builders.
type TaskHistory func(*sql.Selector)

// TradingAccount is the predicate function for tradingaccount builders.
type TradingAccount func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
