// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authentication is the predicate function for authentication builders.
type Authentication func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
