### Retrieve and save token.
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

> {% client.global.set("auth_token", response.body.token); %}

### Bearer auth with token.
GET http://localhost:8080/api/v1/protected
Authorization: Bearer {{auth_token}}

