/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Falcon API
 * This is a crypto trading bot API
 * OpenAPI spec version: 1.0
 */

export interface ModelUser {
  created_at?: string;
  id?: string;
  name?: string;
  timezone?: string;
  updated_at?: string;
}
