/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Falcon API
 * This is a crypto trading bot API
 * OpenAPI spec version: 1.0
 */
import type { ModelTask } from './modelTask';
import type { ModelTradingAccount } from './modelTradingAccount';

export interface V1TaskIndexResponse {
  selected_tasks?: ModelTask[];
  selected_trading_account?: ModelTradingAccount;
  trading_accounts?: ModelTradingAccount[];
}
