import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from "react";
import Providers from "@/app/providers";
import {NavigationBar} from "@/components/navigation-bar";
import {Toaster} from "@/components/ui/toaster";
import {getServerSession} from "next-auth";
import SessionProvider from "@/lib/session"

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default async function RootLayout({children,}: { children: React.ReactNode }) {
    const session = await getServerSession()

    return (
        <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
        <Providers>
            <SessionProvider session={session}>
                <NavigationBar/>
                {children}
                <Toaster/>
            </SessionProvider>
        </Providers>
        </body>
        </html>
    )
}
